#!/usr/bin/env bash
# Accepts 4 paremeters
# Displays usage if less than 3 parameters passed
# scp must transfer the file to the user home directory ~/
# Strict host key checking must be disabled when using scp

if [ "$#" -le 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2":~/
fi
