#!/usr/bin/env bash
# Parse Apache log file in list format:
#	Groups visitors by IP and HTTP status code
#	Exact format must be: OCCURENCE_NUMBER IP HTTP_CODE
# 	Ordered from the greatest to the lowest number of occurrences

awk '{print $1 " " $9}' apache-access.log | sort | uniq -c | sort -rn
