#!/usr/bin/env bash
# Outputs 'Best School'. Outputs Hi on the 9th iteration

index=0
while [ $index -lt 10 ]
do
  if [ $index -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( index++ ))
done
