#!/usr/bin/env bash
# displays numbers from 1 to 20 in addition to:
# 	bad luck from China for the 4th loop iteration
#	bad luck from Japan for the 9th loop iteration
#	bad luck from Italy for the 17th loop iteration

index=1
while [ $index -le 20 ]
do
	echo "$index"
	case $index in
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17") echo "bad luck from Italy";;
	esac
	(( index++ ))
done
